version: '3.8'

services:
  postgres:
    image: postgis/postgis:14-3.2
    container_name: grea-postgres
    environment:
      POSTGRES_DB: gujarat_real_estate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - grea-network

  redis:
    image: redis:7-alpine
    container_name: grea-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - grea-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: grea-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rera.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - grea-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: grea-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: gujarat_real_estate
      DB_USER: postgres
      DB_PASSWORD: postgres123
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - grea-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: grea-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - grea-network

networks:
  grea-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  pgadmin-data: